### PR TITLE
Missing info about queue size per partition

### PR DESCRIPTION
**Pull request by deivydas**
There is a lack of information of current queue size per partition and is useful to have this information

### CODE REVIEW

**Comment by vchekan** [comment]
I am not sure how do you get this info. You declared PartitionQueueInfo public, but it is contained in Producer._allPartitionQueues which is private. So how do you manage to get a hold of PartitionQueueInfo.QueueSize?

Another question is how do you know when size is changed? Polling?
I can think of better way. I've added an event (Rx) and it can be utilized in the following way:
https://github.com/ntent-ad/kafka4net/blob/66f69e4c319f15a88c9d0555cb26b2ed624e4c16/tests/RecoveryTest.cs#L904

Please let me know if this address your needs.

**Comment by deivydas** [comment]
There was another public property created which returned the _allPartitionQueues. However an event is fine by me, so I am looking forward when this will be pushed to master. Thanks for the quick reply.

**Comment by vchekan** [comment]
Ah, missed that public.
It's already in master and published to nuget.org.

**Comment by deivydas** [comment]
Great, thank you.

**Pull request closed without merging**
